services:

  opencep-service:
    image: python:3.9-alpine
    container_name: opencep
    environment:
      BROKER_HOST: rmq
      BROKER_PORT: 5672
      BROKER_USER: user
      BROKER_PASS: pass
      QUEUE_NAME: ingestion_queue
      EXCHANGE_NAME: citibike_exchange
      ROUTE_KEY: output
    working_dir: /opt/app
    volumes:
      - ./pattern_recogniser:/opt/app
    command: ["/bin/sh", "-c", "pip install -r requirements.txt && python main.py"]
    ports:
      - "8080:8080"
    networks:
      - projectnet

  data-ingestion:
    image: python:3.12.11-alpine
    container_name: data-ingestion
    depends_on:
      - rmq
    environment:
      BROKER_HOST: rmq
      BROKER_PORT: 5672
      BROKER_USER: user
      BROKER_PASS: pass
      QUEUE_NAME: ingestion_queue
      EXCHANGE_NAME: citibike_exchange
      ROUTE_KEY: input
      DATAFILE: /datasets/202508-citibike-tripdata_1.csv
    command: ["/bin/sh", "-c", "pip install -r requirements.txt && python ingestion.py"]
    working_dir: /opt/app
    volumes:
      - ./data-ingestion:/opt/app
      - ./data/dataset:/datasets
    networks:
      - projectnet

  rmq:
    image: rabbitmq:3-management
    container_name: rmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    networks:
      - projectnet

  
volumes:
  grafana-storage: {}

networks:
  projectnet:
    driver: bridge